### ISSUE TITLE
Create the database

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursApi#2]
With one table:
- CustomerInfoRequest:
  - CustomerInfoRequestId
  - CustomerInfoRequestEmail
  - CustomerInfoRequestLastName
  - CustomerInfoRequestFirstName
  - CustomerInfoRequestMessage
  - CustomerInfoRequestStatus with possible values: TBP (for to be processed) RTC (for replied to client), RQC (for request closed).

You can decide about the size and type of each column as I have little to detail that at the present moment.

**_Important:**_ be sure the size of CustomerInfoRequestMessage is the same of the limit on the form input in the view so that we are sure that the customer cannot type more than he can.

**Comment by damirius** [comment]
@WebDevJL 

Entity on feature_customerrequest branch. Don't forget to run `php bin/console doctrine:schema:update --force` to create/update customerrequestinfo table.
