### ISSUE TITLE
Patch call /customerinforequests/id/sentemails and removal of email sending

### ISSUE THREAD

**Issue by damirius** [Puzzlout/TrekToursApi#25]
See https://github.com/Puzzlout/TrekToursFlyer/issues/153 and https://github.com/Puzzlout/TrekToursFlyer/issues/153

We are moving email sending to the app side, we are adding new call to the API for patching customerinforequests with new fields `admin_email_sent_date` and `client_email_sent_date`

**Comment by damirius** [comment]
@WebDevJL 

On feature_customerrequest branch

**Comment by WebDevJL** [comment]
@damirius do we agree that to test that and
https://github.com/Puzzlout/TrekToursFlyer/issues/153, I can just run the
refresh script with env=prod on Api repo and then on the flyer repo on a C9
workspace ?

Thanks.

## 

Jérémie Litzler

**Comment by damirius** [comment]
@WebDevJL 

That should work. I think that c9 workspace is on master branch for both repos? If that's so that can be done after the merge

**Comment by WebDevJL** [comment]
@damirius no the default branch is dev. Master is the branch for live and
complete product. Can you merge to dev and test on C9 workspace? I'm
expecting to receive email notifications, contact@puzzlout.com as admin
email and jeremie.litzler@gmail.com as client email. That's validate your
dev.

## 

Jérémie Litzler

**Comment by WebDevJL** [comment]
@damirius I see this working since the dates are set in the DB.
