### ISSUE TITLE
Create a service "customer/getInfoRequests"

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursApi#3]
Enable 1 parameter as an object with some basic filters:
- limit
- from date
- from date

Return a list of requests.

**Comment by damirius** [comment]
@WebDevJL 

There's a lot of new stuff on the branch. There are 4 api endpoints for customerinforequests now. Also added template and email sending after successful creation of new CustomerInfoRequest, added validations for params, exception handler which will display nicer errors in case of invalid submissions. Patch method for updating the status from TBP to RCQ or RTC. Also a call for singular get.
ApiDocs are done also, you can see them at `/doc`, you will have overview of everything done. Plus you will see 'Sandbox' button on each of the endpoints which will let you test them.

**Comment by WebDevJL** [comment]
@damirius I have changed the endpoint URLs to "customer/action". Please take this into account for unit testing. Thanks

**Comment by damirius** [comment]
@WebDevJL 

I tried to go with RESTful "standard", that's the reason of endpoints are named like that. We can name it however you like no problems

**Comment by WebDevJL** [comment]
@damirius can you share this standard specifications? Thanks.

**Comment by damirius** [comment]
@WebDevJL 

http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#restful
From that link this one also: http://apigee.com/about/blog/technology/restful-api-design-nouns-are-good-verbs-are-bad

http://www.restapitutorial.com/lessons/restfulresourcenaming.html
https://philsturgeon.uk/rest/2014/05/11/restful-urls-actions-need-not-apply/

Action endpoints are more in the terms of SOAP where we call specific actions, REST is more resource based where we call a method on specific resource or collection of resources.

**Comment by damirius** [comment]
@WebDevJL 

Can you tell me if you want to leave the endpoints like they are now or do you want to change them back? I just need confirmation, because I want to create calls in the flyer website which will save those entries.

Thanks

**Comment by WebDevJL** [comment]
@damirius You can revert the change since you followed the RESTFull spec. I am currently not available to make the change. Thanks.
