### ISSUE TITLE
Implement Lexik JWT Bundle

### ISSUE THREAD

**Issue by damirius** [Puzzlout/TrekToursApi#6]
Setup for JWT API authentication

**Comment by WebDevJL** [comment]
@damirius so translations in the API?

**Comment by damirius** [comment]
@WebDevJL 

No, just for authentication. Lexik has both JWT and translation bundle, JWT is for authenticating with Bearer token. Want to implement it so we have a login for API. After that we have to use authentication from API project for Flyer website so that when the user logs in he is checked in the API db. That's little more complicated since I'll have to write custom authenticator which will work with our firewall on Flyer website.

Edit: It sound little complicated, but I guess it is :). The point is that we want to use APIs authentication as for all websites, so we have to setup flyer to use APIs users for access checks. I think I will find a way to make it work

**Comment by WebDevJL** [comment]
@damirius We will not need to auth from API for the Flyer. That will come when we start the storefront work.

The main goal is to build the flyer with the least complexity. It is already more complex than I thought. But so far, I'm happy with you did. 

Is that ok?

**Comment by damirius** [comment]
@WebDevJL 

Great, since it will take some time. I mean some time like few hours at best, not something I'll spend 10 days on, but I guess most of the tasks were smaller in comparison.

It's not a problem we can do it later, for now we can use that "in_memory" provider which uses that user:password combo that I sent you over the email. I'm just little worried about those calls to status update, since I saw one issue which implements status setting. Anyone will be able to set the status of the CustomerInfoRequest to anything they want if they know the endpoint for it.

**Comment by WebDevJL** [comment]
@damirius good for me! Thanks.

**Comment by damirius** [comment]
@WebDevJL @gsouvik 

OK this one is important for further implementations.
I've integrated Lexik's JWT Authentication bundle (not to be confused with translation bundle since same guys made this one).
For JWT to function we must generate public and private SSL keys. We are storing them in `/var/jwt/` as `public.pem` and `private.pem` (path can be changed, but this is the usual place to store them).
I've commited generated ssl keys, but best practice is to generate new ones of course. If you already have `openssl` (it's preinstalled on most unix distributions) installed go to `/var/jwt/` and you can run this commands from your console:
`openssl genrsa -out ./private.pem -aes256 4096`
`openssl rsa -pubout -in ./private.pem -out ./public.pem`
First command is for generating private key and will ask you for passphrase, type one you will be asked to confirm it.
After that second command is for generating public key.

So you should have both of them stored in `/var/jwt/`. If you want you can try to use ones that I've commited, but we should create new one for live site. In any case take a look at `/app/config/parameters.yml.dist` and you'll see few new lines regarding this keys. Their location and more important their passphrase. Copy those lines into your local `parameters.yml` and change the passphrase if you generated the files, if you didn't you can type in the passphrase which will I provide over the mail for you.

You can try to test the API now. If you don't have the user created you can create new one now.
We are using FOSUserBundle here so the command is `php bin/console fos:user:create username email password --super-admin`, this will create new user and store it in the db (replace username, email, password with whatever you like), `--super-admin` will create user with super admin role.

Create an API POST call to `/login` (that's our endpoint for submitting login info), with this parameters `_username=username,_password=password`, don't forget "_". You'll get JSON response with token in it. We can send the token through `Authorization` when we make the calls to other endpoints like GET `/customerinforequests` which will prove that we are logged in. Full header looks like this `Authorization: Bearer {token}`, so header is called `Authorization` and value is `Bearer {token}` where {token} is token we got after login call.

If you have trouble with getting this working, check your Apache configuration. Ypu'll see that I've added few lines to `.htaccess` file in the `/web/` directory, but if you created virtual host and setup `AllowOverride None` there that file will not work and you have to add those lines to your vhost.conf.

```
    # Rewrite
    RewriteCond %{HTTP:Authorization} ^(.*)
    RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
```

@WebDevJL 

For setting up travis we must use that config file for it that I commited and we must create test users so we can test login and protected calls.
We just need to add `php bin/console fos:user:create test test@test.com test --env=test --super-admin` which will create superadmin in the test database.
Also we must setup parameters for ssl keys pass phrase and path.
If you want, I can play with that once you merge this stuff together so that I can test it on my side properly and add few stuff to that `.travis.yml` file it's not a problem.

Thank you for taking your time to read through all this text

**Comment by WebDevJL** [comment]
@damirius 

Regarding Travis CI, you can already test it as each commit on a given branch is built. See here: [for the Flyer](https://travis-ci.org/Puzzlout/TrekToursFlyer/branches) and [for the Api](https://travis-ci.org/Puzzlout/TrekToursApi/branches).

Regarding the procedure to test all that, here is my feedback:
1. I have switch to `feature_authentication` branch.
2. I ran `cd var/jwt/`
3. I ran `openssl genrsa -out ./private.pem -aes256 4096` and then `openssl rsa -pubout -in ./private.pem -out ./public.pem`. **_All good**_.
4. I went back to the root of the project: `cd ../../`
5. I ran `sh CloudDeploy/Project/TrekTours/Api/refresh.sh prod` where I was asked to confirm:
   - the path of private.pem (hit enter since I stored in the default location)
   - the path of public.pem (hit enter since I stored in the default location)
   - I typed the same passphrase I entered while running step 3 above
   - I left the default ttl
6. I ran `php bin/console fos:user:create oneuser test@test.com testpass --super-admin`. **_All good**_.
7. I tested the `/me` endpoint and got HTTP/401:
   ![screen shot 2016-06-28 at 06 58 34](https://cloud.githubusercontent.com/assets/3506074/16404278/d21f5fc8-3cfd-11e6-8b55-09e38cf14c85.png)

So what am I missing?

Is it mandatory to setup the vhosts? On Cloud 9, which is our current hosting to showcase the project to the client, I can't setup vhosts.

Locally, I am not using vhosts. My urls are:
- API: http://localhost/TrekToursApi/web/doc
- Flyer: http://localhost/TrekToursFlyer/web

Thanks for the analysis

**Comment by damirius** [comment]
@WebDevJL 

When you are creating test user be sure to add `--env=test` to create it in the testdatabase. `phpunit` is run by default in that environment. If you are missing test database create it first with `php bin/console doctrine:database:create --env=test` then run `php bin/console fos:create:user oneuser test@test.com testpass --super-admin`

`/me` endpoint isn't used for login, it is used when you are already logged in to fetch your profile. To login make a POST request to `/login` endpoint with `_username=oneuser` and `_password=testpass` parameters.

**Comment by WebDevJL** [comment]
@damirius I am trying to make it work in prod environnement. If the procedure is different for PROD, I need the procedure for all environnement, please. I have a dev db already. Can I test that with it?

And my mistake for the /me endpoint. I misread your comment.

**Comment by damirius** [comment]
@WebDevJL 

If you are testing it in prod environment it's all the same expect you don't need to use `--env=test`. Just make a POST call to `/login` first to login and get your token, after that you can use that sandbox mode of apidocs there to add your token to authorization header in this format: `Authorization: Bearer {Token}`

**Comment by WebDevJL** [comment]
@damirius Still unable to make this work. The old "admin" user is not working anymore, which I guess is normal since we use the JWT auth now.

I downloaded a clean copy of the api repo, ran the `CloudDeploy/Project/TrekTours/Api/install.sh prod`(check it out here: https://github.com/Puzzlout/CloudDeploy).

I downloaded a clean copy of the flyer repo, ran the `CloudDeploy/Project/TrekTours/Flyer/install.sh prod`(check it out here: https://github.com/Puzzlout/CloudDeploy).

I can view the website all right but can't login to the admin area.

Would the vhosts configuration be the problem?

**Comment by WebDevJL** [comment]
@damirius Here is exactly my procedure:

```
My projects are under the document root of Apache: /www/sites

I have the CloudDeply repository cloned under the document root.

On Api repository:
cd /www/sites
git clone https://github.com/Puzzlout/TrekToursApi.git
cd TrekToursApi
sh ../CloudDeploy/Projects/TrekTours/Api/install.sh prod
cd var/jwt/
openssl genrsa -out ./private.pem -aes256 4096
#typed the passphrase
#confirmed the passphrase
openssl rsa -pubout -in ./private.pem -out ./public.pem
#retyped the same passphrase as above
 cd ../../
 sh ../CloudDeploy/Project/TrekTours/Api/refresh.sh prod
 php bin/console fos:user:create oneuser test@test.com testpass --super-admin

On Flyer repository:
cd /www/sites
git clone https://github.com/Puzzlout/TrekToursFlyer.git
cd TrekToursFlyer
sh ../CloudDeploy/Projects/TrekTours/Flyer/install.sh prod

Went to http://localhost/TrekToursFlyer/web/admin
Entered the login "oneuser:testpass"
Got the error "Bad credentials"
```

What do you see that I missed?

**Comment by damirius** [comment]
@WebDevJL 

Are you getting "Bad credentials" message or "Invalid credentials" message above the form in red alert div on the /admin?

We are using some sort of CUrl wrapper so make sure you have it installed, it's probably not that but just want to make sure. If you have one you can try to make curl request to login, with _username, _password parameters to see if api is working correctly and it's generating token. With that token you then can go to http://localhost/TrekToursApi/web/doc to see the documentation and sandbox open up "/me" endpoint for testing. Try adding your token to the header and make a call from there. Header is 'Authorization' value is 'Bearer {Token}'. Where {token} is your generated token you got from calling /login.
I want to locate origin of the problem first, it looks like it is on API, but just want to make sure and to get to bottom of this.
Thank you for your patience

**Comment by WebDevJL** [comment]
@damirius Yes, I get "Bad credentials". What is the name the curl wrapper? What can I run to check if it is installed?

I will try the login later on. For now, I need to find us a designer!

**Comment by damirius** [comment]
@WebDevJL 
I was asking about that message because of exact wording. You can see in this video that trying to login with non existing user/pass combo gives "Invalid credentials" message not "Bad credentials".
https://drive.google.com/file/d/0B7Laiv0PjSvDN3FnQk92V1p5X3M/view

Api is returning "bad credentials" 401 response in that case, but our authenticator on the flyer website process that response and displays "Invalid credentials" instead as you can see. I want to see if error is on flyer or on api.
In any case the best way to determine that is to make call to http://localhost/TrekToursApi/web/login with `_username` and `_password` parameters and see if that calls return valid response which is json with `token`.

To see if the curl is installed (we need it for flyer). If you want to see if curl is intalled just type `curl -V` in shell. If you want to check if curl is installed as php module I believe you can run `curl_version()` in php script. We are using some CircleRestClientBundle, but it's just a wrapper that runs built in curl. So if regular curl functions work wrapper will work too.

**Comment by WebDevJL** [comment]
@damirius I shall try that.
